stages:
  - test
  - build
  - deploy

# ng-test:
#   stage: test
#   image: whatshiywl/angulartester:1.0.1
#   script:
#     - ./test.sh

docker-build:
  stage: build
  image: whatshiywl/gcp-node-builder:1.0.0
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - mv /build/build.sh $CI_PROJECT_DIR
    - mv /build/get-version.sh $CI_PROJECT_DIR
    - ./build.sh
  artifacts:
    reports:
      dotenv: build.env
  # dependencies:
  #   - ng-test

cloud-deploy:
  stage: deploy
  image: whatshiywl/gcp-node-deployer:1.0.0
  script:
    - deploy.sh
  dependencies:
    - docker-build
