stages:
  - build
  - deploy

docker-build:
  stage: build
  image: docker
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - build.sh
  artifacts:
    reports:
      dotenv: build.env

cloud-deploy:
  stage: deploy
  image: google/cloud-sdk
  script:
    - deploy.sh
  dependencies:
    - docker-build
