

stages:
  - build
  - before-deploy
  - deploy

build-job:
  stage: build
#  image: google/cloud-sdk
  image: docker
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - tVersion=$(sh ./get-version.sh)
    - version=${tVersion:-1.0}
    - docker build . -t $GCP_PROJECT/$GCP_SERVICE:$version

test-job:
  stage: before-deploy
  image: docker
  services:
    - docker:dind
  script:
    - docker images

deploy-job:
  stage: deploy
  image: google/cloud-sdk
  script:
    - echo deploy stage
#    - echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-sdk -y
#    - gcloud auth activate-service-account --key-file $GCP_SERVICE_KEY
#    - gcloud config set project $GCP_PROJECT
#    - gcloud builds submit . --config=cloudbuild.yml


# test-job1:
#   stage: test
#   script:
#     - echo "This job tests something"

# test-job2:
#   stage: test
#   script:
#     - echo "This job tests something, but takes more time than test-job1."
#     - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
#     - echo "which simulates a test that runs 20 seconds longer than test-job1"
#     - sleep 20

# deploy-prod:
#   stage: deploy
#   script:
#     - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
